### PR TITLE
Fix for field type blocks

### PR DESCRIPTION
**Pull request by tiito78**
Fix for field type blocks. Prevent from getting "__internal" error on blocks.

### CODE REVIEW

**Comment by doenietzomoeilijk** [comment]
I can confirm this (together with bolt/bolt#7705) fixed the problem with translations for Block field types in a Bolt 3.6 + Translate 4.1.4 setup.

**Comment by SahAssar** [comment]
I'll let/force @bobdenotter  have the call on this since he has had more involvement here lately than me. Personally it feels like it's repeating the hack I had to do to make repeaters work which means that it is ugly, but probably works unless you poke it too much.

As a hold-over until we get bolt v4 I'd be fine with it.

**Comment by tiito78** [comment]
that's what is its.. the same hack for repeaters. Feel free to use it, or just leave it. As @doenietzomoeilijk wrote the hack is doing the work, and me my self can also confirm that.

**Comment by bobdenotter** [comment]
Thanks, @tiito78! 👍 

Let's ship, and do it better in v4. :shipit:

**Pull request merged**
