### PR TITLE
Also note that you should use `true` and not `1` for translatable

### PR DESCRIPTION
**Pull request by evertalbers**

### CODE REVIEW

**Comment by JarJak** [comment]
@evertalbers can you fix issue link?

**Comment by evertalbers** [comment]
You mean "Fix the cause"? No, I'm sorry, I don't have the proper php skills :-(

**Comment by JarJak** [comment]
No, I mean the `Fixes: #1555` part, you provide URL of this issue?

**Comment by bobdenotter** [comment]
Thanks, @evertalbers.. Apologies for taking so long to merge it in.

**Pull request merged**
